[package]
name = "enigma-tools-t"
version = "0.1.0"
authors = ["Elichai-Turkel <elichai@enigma.co>"]
description = "Tools used by the trusted part of the Enigma core and Principal node."
repository="https://github.com/enigmampc/enigma-core/tree/master/enigma-tools-t"
keywords =["enigma","enclave","sgx","remote attestation"]

[dependencies]
tiny-keccak = "1.4.1"
libsecp256k1 = { git = "https://github.com/enigmampc/libsecp256k1-rs.git" }
ring = { git = "https://github.com/enigmampc/ring.git", rev = "sgx-0.12.1" }
# errors handling 
failure = { version = "0.1.1", default-features = false, features = ["derive"] }

[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_tstd]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_trts]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_types]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

# quote
[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_tse]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

# sealing 
[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_tseal]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"
